version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: stord/url-shortener-exercise
    ports:
      - "5000:5000"
    environment:
      - APP_PORT=5000
      - DATABASE_DATABASE=app_db
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
    links:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
